/// Flutter icons El
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  El
///      fonts:
///       - asset: fonts/El.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class El {
  El._();

  static const _kFontFam = 'El';
  static const String? _kFontPkg = null;

  static const IconData eye = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locaion_pin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autorenew = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
